version: '3'  
services:  
  # db:  
  #   image: postgres:latest  
  #   restart: always  
  #   ports:  
  #     - 5432:5432  
  #   environment:  
  #     POSTGRES_DB: js-playground-db  
  #     POSTGRES_USER: postgres  
  #     POSTGRES_PASSWORD: password  
  #   volumes:  
  #     - db:/var/lib/postgresql/data  
  api:
    profiles: ["dev"]
    build:
      context: ./apps/hono-rest-api
      dockerfile: ./Dockerfile.local
    ports:
      - "4000:4000"
    volumes:
      - ./apps/hono-rest-api:/app
    # environment:
    #   DATABASE_URL: "postgres://postgres:password@db:5432/js-playground-db?schema=public"
# volumes:  
  # db: